### ISSUE TITLE
Unable to exec ape unless explictly run as shellscript

### ISSUE THREAD

**Issue by gizlu** [jart/cosmopolitan#586] opened 2022-09-02 15:00 UTC
I'm unable to run apes unless I explicitly run them as shellscripts
`Cannot open assembly './hello.com': File does not contain a valid CIL image.`
![image](https://user-images.githubusercontent.com/46008403/188177102-61ee0851-776e-47e1-b2d6-00e58f126564.png)
ape version: 2.0.1, hello world built as in README

**Comment by pkulchenko** [comment] 2022-09-02 15:11
@gizlu, do the steps listed in the [installation](https://redbean.dev/#install) section (after "If you use Linux and want to use binfmt_misc...") work for you? This may be a duplicate of #356.

**Comment by gizlu** [comment] 2022-09-02 15:15
Yes, it works after registering ape handler

**Comment by jart** [comment] 2022-09-04 04:37
Thanks for helping our friend @pkulchenko. Contributions welcome if anyone wants to update the README to help WSL users more. We also intend to upstream APE support into the Linux kernel to sidestep these binfmt_misc struggles entirely.

**Closed by jart** 2022-09-04 04:37 UTC
Labels: support
