### ISSUE TITLE
Building from sources seems broken on Linux

### ISSUE THREAD

**Issue by wandrien** [jart/cosmopolitan#891] opened 2023-09-05 07:07 UTC
Arch Linux, kernel version 6.4.9

The latest commit that sucessfully builds for me is 9cf2bdc9a806409055bd4d624dc2fa5b03090729, Sep 13, 2022.

I tried all the latest commits listed at https://github.com/jart/cosmopolitan/commits/master/build/bootstrap/compile.com
Here is the results:

```
$ git clean -dxf
$ git checkout 40eb3b9d5d7df65181c0b229282120443cdbec64
$ build/bootstrap/make.com
♥cosmo
ape error: build/bootstrap/compile.com: APE phdrs must be 4096-aligned and 4096-padded
ape error: build/bootstrap/compile.com: APE phdrs must be 4096-aligned and 4096-padded
make.com: *** [build/rules.mk:197: o/ape/ape.internal.h.ok] Error 127
Status: 2
```

```
$ git clean -dxf
$ git checkout 3dc86ce154b8b72840eade1b48e752114d21f686
$ build/bootstrap/make.com
♥cosmo
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** Deleting file 'o//.x'
    28,843⏰     28,243⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_ape_internal_h_ok.tsxjd3/o_ape_ape.internal.h.ok ape/ape.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,284⏰     14,029⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_idata_internal_h_ok.18ofv0/o_ape_idata.internal.h.ok ape/idata.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    15,846⏰     15,181⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_macros_internal_h_ok.7t93en/o_ape_macros.internal.h.ok ape/macros.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    13,820⏰     13,338⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_relocations_h_ok.e1vl2e/o_ape_relocations.h.ok ape/relocations.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,890⏰     14,544⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_sections_internal_h_ok.x0zt0n/o_ape_sections.internal.h.ok ape/sections.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** [ape/ape.mk:233: o//ape/ape.o] Error 127
make.com: *** Deleting file 'o//ape/ape.o'
Status: 2
```

```
$ git clean -dxf
$ git checkout f7ae50462ad280f07944111fc4c876ae976d4be1
$ build/bootstrap/make.com
♥cosmo
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** Deleting file 'o//.x'
    28,118⏰     27,501⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_ape_internal_h_ok.jv6ywm/o_ape_ape.internal.h.ok ape/ape.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    15,422⏰     14,821⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_idata_internal_h_ok.pqkpuq/o_ape_idata.internal.h.ok ape/idata.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    18,581⏰     17,958⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_macros_internal_h_ok.osqqz0/o_ape_macros.internal.h.ok ape/macros.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,578⏰     14,193⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_relocations_h_ok.zddmlf/o_ape_relocations.h.ok ape/relocations.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,423⏰     14,126⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-map=/tmp/cosmopolitan= -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_sections_internal_h_ok.7gridp/o_ape_sections.internal.h.ok ape/sections.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** [ape/ape.mk:234: o//ape/ape.o] Error 127
make.com: *** Deleting file 'o//ape/ape.o'
Status: 2
```

```
$ git clean -dxf
$ git checkout a2d269dc389d46f8d10873177d210648a7e9d193
$ build/bootstrap/make.com
♥cosmo
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** Deleting file 'o//.x'
    14,561⏰     14,260⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_ape_internal_h_ok.9cm23j/o_ape_ape.internal.h.ok ape/ape.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    15,974⏰     15,455⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_idata_internal_h_ok.8dqklw/o_ape_idata.internal.h.ok ape/idata.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,919⏰     14,675⏳  11,520k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_macros_internal_h_ok.3imsqq/o_ape_macros.internal.h.ok ape/macros.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    15,773⏰     15,412⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_relocations_h_ok.hqc4z2/o_ape_relocations.h.ok ape/relocations.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    15,372⏰     14,340⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o /tmp/cosmopolitan/o/tmp/o_ape_sections_internal_h_ok.0pfsnz/o_ape_sections.internal.h.ok ape/sections.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** [ape/ape.mk:234: o//ape/ape.o] Error 127
make.com: *** Deleting file 'o//ape/ape.o'
Status: 2
```

```
$ git clean -dxf
$ git checkout 18bb5888e1302aa3e198eff5bf3d880337f79995
$ build/bootstrap/make.com
Makefile:91: please run ape/apeinstall.sh if you intend to use landlock make
♥cosmo
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** Deleting file 'o//.x'
    14,827⏰     14,413⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o o/ape/ape.internal.h.ok ape/ape.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    16,048⏰     15,573⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o o/ape/idata.internal.h.ok ape/idata.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    17,331⏰     16,940⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o o/ape/macros.internal.h.ok ape/macros.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    14,517⏰     13,950⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o o/ape/relocations.h.ok ape/relocations.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
    17,162⏰     16,433⏳  11,648k       0iop o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -DCOSMO -DMODE="" -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -std=gnu2x -fno-inline-functions-called-once -xc -g0 -o o/ape/sections.internal.h.ok ape/sections.internal.h -fdiagnostics-color=always -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
make.com: build/bootstrap/compile.com: execv failed: EACCES
make.com: *** [ape/ape.mk:282: o//ape/ape.o] Error 127
make.com: *** Deleting file 'o//ape/ape.o'
Status: 2
```

**Comment by ingenieroariel** [comment] 2023-09-19 18:02
Could you try with the following on a recent checkout?

```
./ape/apeuninstall.sh
./ape/apeinstall.sh
./build/bootstrap/make.com
```

I am hoping the problem is a very old APE installation, which could be fixed by the above.

**Comment by conradolandia** [comment] 2023-09-27 00:46
I can confirm that the compilation fails and the proposed solution **does not** work. Arch Linux here. Different error. Running it with sudo doesn't change anything. 

```
/opt/cosmo> build/bootstrap/make.com

failed to move output file
/opt/cosmo/o/tmp/o__dsp_mpeg_clamp4int256_core_o.b0d3mq/o__dsp_mpeg_clamp4int256-core.o
o//dsp/mpeg/clamp4int256-core.o
o/third_party/gcc/bin/x86_64-linux-musl-gcc -Wall -Werror -frecord-gcc-switches -O2 -fno-code-hoisting -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -fpatchable-function-entry=18,16 -g -Wa,-W -Wa,-I. -Wa,--noexecstack -D_COSMO_SOURCE -DMODE="" -nostdinc -iquote . -DSYSDEBUG -DFTRACE -include libc/integral/normalize.inc -c -o o//dsp/mpeg/clamp4int256-core.o dsp/mpeg/clamp4int256-core.S -fdiagnostics-color=always -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
consumed 10,015µs wall time
ballooned to 11,264kb in size
needed 9,979us cpu (58% kernel)
caused 2,418 page faults (100% memcpy)
5 context switches (100% consensual)
performed 0 read and 24 write i/o operations

make.com: *** [build/rules.mk:48: o//dsp/mpeg/clamp4int256-core.o] Error 90
make.com: *** Deleting file 'o//dsp/mpeg/clamp4int256-core.o'
```

**Comment by jart** [comment] 2023-10-04 00:38
I can't reproduce this at head. What you have is an APE loader version mismatch that happened several versions ago. The `ape/apeuninstall.sh` and then `ape/apeinstall.sh` commands should nail it. Especially if you use binfmt_misc. There's only one exception. It's if you're using an old cosmo binary to execve() a newer cosmo binary that requires the newer ape loader.

We've long since updated the build/bootstrap/ binaries. Chances are you're working on an old revision of the cosmo repo. If it's not that, then you've probably got an old cosmo build of something like landlock make.com, or bash.com, etc. hiding on your $PATH. You can tell if this is the case, if files like `~/.ape-1.3` (or so) appear even though we're on 1.8.

**Closed by jart** 2023-10-04 00:38 UTC

**Comment by jart** [comment] 2023-10-04 00:40
It might also be the case that you've downloaded an old binary from justine.lol possibly? Those might need to be updated.

**Comment by realgdman** [comment] 2023-11-01 23:49
I had several issues building from source and one was exact message as https://github.com/jart/cosmopolitan/issues/891#issuecomment-1736489895
Possible reason could be, that bundled version inside `cosmopolitan-3.0.1.tar.gz` is `ape-1.7` but in `cosmos-3.0.1.zip` is `ape-1.8`. So really `/usr/bin/ape -h` reported 1.7. I haven't been able to build yet. but seeing progress when swapped version in cosmo/o/ape.
