### ISSUE TITLE
Segmentation fault: 11 on M1 Mac

### ISSUE THREAD

**Issue by legendre6891** [jart/cosmopolitan#432] opened 2022-06-18 17:55 UTC
Hi there! This is really impressive work!

I've gotten this to work on my Windows computer. However, on my M1 MacBook, I get the following error 

```
(in zsh) $ bash
bash-3.2$ ./redbean-2.0.3.com -v
Segmentation fault: 11
```

Happy to give more debug output (just don't know how to), if needed. Thanks!

**Comment by pkulchenko** [comment] 2022-06-18 18:00
Is this a duplicate of #429?

**Comment by legendre6891** [comment] 2022-06-18 18:04
Possibly? Unfortunately, I am not sure what is Rosetta. Also, the redbean used is the prebuilt one (downloaded via curl), not built from source, in case that matters?

**Comment by pkulchenko** [comment] 2022-06-18 18:11
Rosetta is a translation process to run apps that contain x86_64 instructions (which is what Redbean/Cosmopolitan has) on Apple silicon (which is what M1 is). See apple [docs on this](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).

Can you add `--ftrace` option to redbean? I'm curious if there is any additional output (but most likely not if it's the same issue as is discussed in #429).

**Comment by legendre6891** [comment] 2022-06-18 19:02
Thanks for the explanations, @pkulchenko. Agreed it is the same issue. In any case, here is my output with `--ftrace` (it is the same error output).
```
bash-3.2$ ./redbean-2.0.3.com --ftrace
Segmentation fault: 11
```

**Comment by pkulchenko** [comment] 2022-06-18 19:04
@legendre6891, ok; thank you for the confirmation! I'll close this one and we can continue the discussion in #429.

**Closed by pkulchenko** 2022-06-18 19:04 UTC
