### ISSUE TITLE
cosmoc++ seems not work on Windows

### ISSUE THREAD

**Issue by yanecc** [jart/cosmopolitan#1311] opened 2024-10-05 18:24 UTC
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/jart/cosmopolitan/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/jart/cosmopolitan/discussions), and have a new and useful enhancement to share.

### Feature Description

support compile with cosmoc++ on Windows

### Motivation

Now, the compiler doesn't work on Windows but works well in the WSL. What stops it?
```
$ cosmoc++ test.cpp -o test.com
cosmocc: fatal error: precompiled headers only supported with ARCH-unknown-cosmo-cc compilers
compilation terminated.
```

**Comment by jart** [comment] 2024-10-06 05:07
I can't reproduce this. Not on Linux. Not on Windows. Are you sure that's the command line invocation you're using?

**Comment by yanecc** [comment] 2024-10-06 07:19
> I can't reproduce this. Not on Linux. Not on Windows. Are you sure that's the command line invocation you're using?

Yes, and I'm using the git-bash on Windows.

**Comment by jart** [comment] 2024-10-06 13:45
Tried that. Can't reproduce. I'm closing this. You need to find out what the issue is before reporting issues. This project doesn't provide technical support.

**Closed by jart** 2024-10-06 13:45 UTC
