### ISSUE TITLE
printvideo.com is not working on Ubuntu 18.04 (conflicting with binfmt_misc?..)

### ISSUE THREAD

**Issue by lithuak** [jart/cosmopolitan#62] opened 2021-02-26 22:28 UTC
Hey, sorry if this is the wrong place to post it, I just wasn't sure where exactly to report (looks like printvideo.com doesn't have it's own repo).

Anyway:

`$ ./printvideo.com`

fails to run with this msg:

`run-detectors: unable to find an interpreter for ./printvideo.com`

and here is my:

```
$ uname -a
Linux blackbox 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x
86_64 x86_64 GNU/Linux`
```

After some digging, it looks like the culprit is [binfmt_misc](https://en.wikipedia.org/wiki/Binfmt_misc) kernel  feature.

Renaming `printvideo.com` to `printvideo` doesn't solve it, thus I assumed that binary format guessing happened by the file header ("MZ..."), not by extension (".com").

Here are the formats registered in my system:

`# ls -l /proc/sys/fs/binfmt_misc/`

```
-rw-r--r-- 1 root root 0 Feb 24 08:22 cli
-rw-r--r-- 1 root root 0 Feb 24 08:22 jar
-rw-r--r-- 1 root root 0 Feb 24 08:22 llvm-6.0-runtime.binfmt
-rw-r--r-- 1 root root 0 Feb 26 06:23 python2.7
-rw-r--r-- 1 root root 0 Feb 26 06:22 python3.6
--w------- 1 root root 0 Feb 26 06:23 register
-rw-r--r-- 1 root root 0 Feb 27 13:38 status
```

The `cli` is our handler:

```
# cat /proc/sys/fs/binfmt_misc/cli 
enabled
interpreter /usr/lib/binfmt-support/run-detectors
flags: 
offset 0
magic 4d5a

```

So, looks like it is `/usr/lib/binfmt-support/run-detectors` who is to run the binary and who fails to do so :/

**Comment by jamesbeebop** [comment] 2021-02-27 13:57
It's not a fix, but you can disable binfmts.

`sudo update-binfmts --disable`

To re-enable:

`sudo update-binfmts --enable`

**Comment by lithuak** [comment] 2021-02-27 14:05
Thanks @jamesbeebop. I'll try to dig deeper when I have time.

**Comment by jart** [comment] 2021-02-27 22:44
If you use binfmt_misc then you need to run the following command:

```sh
sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
```

Then you're good to go!

Marking as duplicate of #2. Note that I don't consider this fully resolved. While a workaround exists we ideally should not need the workaround. I intend to upstream a change in the Linux Kernel, or somewhere, because the upstream tools should be smarter than this.

**Closed by jart** 2021-02-27 22:44 UTC
