### ISSUE TITLE
printvideo.com can't play files with spaces in path

### ISSUE THREAD

**Issue by gavinhoward** [jart/cosmopolitan#11] opened 2020-12-24 17:42 UTC
I run Gentoo `x86_64`. I found `printvideo.com` about six months ago and used it to test terminals. I decided to test `st`, the suckless terminal, and something since 6 months ago changed on Gentoo (a rolling distro) that makes `printvideo.com` fail. I can still make it work on a FreeBSD virtual machine.

After diving into the code, it seems it is a change to the compiler because changing lines like https://github.com/jart/cosmopolitan/blob/master/tool/viz/printvideo.c#L969 to

```
plm_ = plm_create_with_filename(path_);
CHECK_NOTNULL(plm_);
```

makes the error go away, but another shows up on a similar line, and when I fix that one, another shows up.

So it seems to me that the compiler changed, though the issue shows up with both `gcc` and `clang`.

**Comment by jart** [comment] 2020-12-24 18:54
Thanks for the report. It sounds like you've been using Cosmopolitan for quite some time, which is very exciting. I'm assuming you're synced to head? 

DCHECK_NOTNULL can be optimized away, but CHECK_NOTNULL should not have that behavior, unless maybe autotype is somehow broken.

Cosmopolitan should always use the same compiler. The static linux binaries for gcc are stored in the third_party/gcc/ folder. Earlier in the project history, a lot of effort was devoted to getting the entire repository to build with clang. There hasn't been a reason to continue investing that effort, since there aren't static binaries available for it that're small enough to vendor with auto regression testing, gcc works great, and one of the stated goals of this project is to write c without needing devops.

I just tried freebsd 12.1 and it worked ok for me (via ssh in putty) try giving this a whirl:

```
wget http://justinetunney.com/printvideo.com
chmod +x printvideo.com
wget https://justine.storage.googleapis.com/timekiller.mpg
./printvideo.com -xs timekiller.mpg
```

I tried installing Gentoo for you too, but ran into dvorak issues, so sadly not today. It's been 15 years since my last Gentoo install. It was quite a learning experience back then.

**Comment by gavinhoward** [comment] 2020-12-24 19:14
Unfortunately, no, I didn't even know `printvideo.com` was part of Cosmopolitan until today because I didn't know about Cosmopolitan until today. I just found `printvideo.com` while I was deciding whether to run `kitty`, `alacritty`, or stay with Gnome terminal.

It was only today when I had to look at the code for `printvideo.com` to debug it that I found out that it is part of Cosmopolitan. Sorry. But yes, I am synced to HEAD.

With the mpg file you provided, it works. With the mpg file I used, it does not, which is weird because that's the file I used six months ago. What's also weird is that the file I used six months ago works on FreeBSD 12.2 now (in a VM, over `ssh`).

You can get the video I used (converted "Tears of Steel") from [this link][1].

[1]: http://gavinhoward.com/videos/ToS.mpg

**Comment by jart** [comment] 2020-12-24 22:01
Looks OK to me. 

![image](https://user-images.githubusercontent.com/49262/103107100-07303700-45f0-11eb-9f18-fdbbbe2e35b8.png)

Help me understand what doesn't work means. Usually the only time I see this command not work, it's due to the audio subprocess being flaky. For example, sox play and alsa are just so bad at pipes, but the ffplay command tends to do a reasonable job even though it's kind of bloated.

Out of curiosity, how did you find out about printvideo.com?

**Comment by gavinhoward** [comment] 2020-12-24 22:32
I mean something like this:

![Screenshot from 2020-12-24 15-26-48](https://user-images.githubusercontent.com/3172687/103107585-1d90bf80-45fd-11eb-9c1f-aa747f82c3c3.png)

I found `printvideo.com` when I was trying to find a good benchmark for terminal emulators because I wasn't sure I trusted `alacritty`'s claims completely. I just searched something like "images in terminals linux" or something like that.

**Comment by jart** [comment] 2020-12-24 23:19
Ah! That helps a lot. Here's what you need to do:

```
wget https://justine.lol/printvideo/printvideo.com
wget https://justine.lol/printvideo/printvideo.com.dbg
chmod +x printvideo.com
./printvideo.com ~/Videos/Blender\ Institute/ToS.mpg
```

If you run that, then it should print a much more informative error message. Sorry for the terse one! I built the release binary under MODE=tiny since I thought the binary size was cool. But I probably should have been more conservative in anticipation of situations like these.

**Comment by gavinhoward** [comment] 2020-12-24 23:22
```
./printvideo.com: /usr/share/bashdb/bashdb-main.inc: No such file or directory
./printvideo.com: warning: cannot start debugger; debugging mode disabled
error:tool/viz/printvideo.c:872:printvideo.com: check failed
	CHECK_NE(-1, uriparse(&uri_, uristr, strlen(uristr)));
		→ 0xffffffffffffffff (-1)
		!= 0xffffffffffffffff (uriparse(&uri_, uristr, strlen(uristr)))
	EINVAL/err=22/errno:22/GetLastError:0
	/home/gavin/Downloads/printvideo.com \
		/home/gavin/Videos/Blender Institute/ToS.mpg
0x0000000000427599: __die at libc/log/die.c:37
0x0000000000427494: __check_fail at libc/log/checkfail.c:84
0x0000000000408de6: ParseUriOrDie at tool/viz/printvideo.c:872
0x000000000040c100: main at tool/viz/printvideo.c:1635
0x0000000000401ef2: _executive at libc/runtime/executive.S:50
0x000000000040125f: _start at libc/crt/crt.S:57
```

**Comment by jart** [comment] 2020-12-24 23:29
That looks like a bug. If you move the file to a directory that doesn't have a space in the path, then does it work?

**Comment by gavinhoward** [comment] 2020-12-24 23:32
Why, yes, it does. I take it you know what's wrong?

**Comment by jart** [comment] 2020-12-25 00:16
It should be fixed now. Thanks again for the report. New binary release file (MODE=rel) is uploaded too, for your convenience:

 * https://justine.lol/printvideo.com      # 284k ape executable
 * https://justine.lol/printvideo.com.dbg

**Closed by jart** 2020-12-25 00:16 UTC

**Comment by gavinhoward** [comment] 2020-12-25 00:30
Thank you!

**Comment by jart** [comment] 2020-12-25 00:44
You're so welcome. By the way, since you were testing `st`, I have a feeling you might find this code interesting: https://github.com/jart/cosmopolitan/blob/master/tool/build/lib/pty.c It implements the terminal inside [blinkenlights](https://justine.lol/blinkenlights/index.html) and is easily embeddable if you ever felt motivated to make your own terminal.

**Comment by gavinhoward** [comment] 2020-12-25 01:01
Thank you. :)
