### ISSUE TITLE
Cannot run on ArchLinux when mono is installed

### ISSUE THREAD

**Issue by frhun** [jart/cosmopolitan#77] opened 2021-02-28 03:43 UTC
This basically is just what the title says.
Because the Arch package for mono installs a binfmt_misc [1] rule that matches the 'MZ' magic number. [2]
The same thing happens with wine, as it also installs a rule matching 'MZ'.
It is questionable if this is an issue that is even relevant here, because there is quite literally nothing you can really do about it, at least downstream. (Or at least I think we can't)
I thought it belonged here anyway, just to make the search for the problem easier, when people encounter this problem.
I haven't yet looked on other distros, but I think it is safe to assume that many systems will have similar configurations for mono/.NET Core/Wine.
It is kind of frustrating to have something as mundane as this as a real roadblock.

1:
https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html

2: https://github.com/archlinux/svntogit-packages/blob/fb79e86760013662b08c8c013043ab07d682f74f/trunk/mono.binfmt.d

**Comment by jart** [comment] 2021-02-28 05:07
Isn't it horrifying how packages are allowed to install hooks around launching executables? Rest assured, if a rogue package has tuned your system to use binfmt_misc, we have an easy workaround:

```sh
sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
```

I intend to upstream a change with the Linux Kernel real soon that obfuscates the need for this workaround. Marking as duplicate of #2. Thank you for using Cosmopolitan!

**Closed by jart** 2021-02-28 05:07 UTC

**Comment by gudenau** [comment] 2021-05-14 04:03
I just encountered this issue and I can't wait for this to get fixed. Happy kernel hacking!

**Comment by chaserhkj** [comment] 2024-10-05 03:32
> Isn't it horrifying how packages are allowed to install hooks around launching executables? Rest assured, if a rogue package has tuned your system to use binfmt_misc, we have an easy workaround:
> 
> ```shell
> sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
> ```
> 
> I intend to upstream a change with the Linux Kernel real soon that obfuscates the need for this workaround. Marking as duplicate of #2. Thank you for using Cosmopolitan!

Unfortunately this does not work on my current system (which is also arch linux) with mono installed.
This is because of the below unlucky coincidence:
```bash
/proc/sys/fs/binfmt_misc $ cat CLR
enabled
interpreter /usr/bin/mono
flags:
offset 0
magic 4d5a
/proc/sys/fs/binfmt_misc $ cat APE
enabled
interpreter /usr/local/bin/ape
flags:
offset 0
magic 4d5a71467044
```
CLR format's(which is used by mono) magic bytes are APE format's magic bytes' exact prefix. Apparently under this condition the kernel matches against the shorter magic bytes and uses mono for the binary file.

I have to disable mono's registration by `sudo sh -c "echo 0 > /proc/sys/fs/binfmt_misc/CLR"` to make it work.

Or permanently, under Arch Linux, mono's registration can be masked and disabled:
```
sudo ln -s /dev/null /etc/binfmt.d/mono.conf
```

This will create problems with mono apps on my system, but I could not find a better solution.

@jart Please let me know if you think this problem warrants another separate open issue for better tracking and documentation.
