### ISSUE TITLE
Entering a command at the repl fails

### ISSUE THREAD

**Issue by Zulu-Inuoe** [jart/cosmopolitan#428] opened 2022-06-17 16:28 UTC
Windows 10 x64

I fire up either `readbean` or the `redbean-demo`, and while the server works just fine, entering any expression at the repl causes redbean to crash on a bad handle.

Here is a trace calling `Benchmark`. However, this happens for any expression eg. even if I typed in literally `42`.
```
E:\Downloads
λ redbean-demo-2.0.2.com -Zv
I2022-06-17T09:22:44.752970:tool/net/redbean.c:6923:redbean-demo-2:9928] (srvr) listen http://192.168.1.243:8080
I2022-06-17T09:22:44+002998:tool/net/redbean.c:6923:redbean-demo-2:9928] (srvr) listen http://127.0.0.1:8080
V2022-06-17T09:22:44+001000:tool/net/redbean.c:1857:redbean-demo-2:9928] (ssl) could not find non-CA SSL certificate key pair with -addext keyUsage=digitalSignature -addext extendedKeyUsage=serverAuth
V2022-06-17T09:22:44+001000:tool/net/redbean.c:1860:redbean-demo-2:9928] (ssl) could not find CA key signing key pair with -addext keyUsage=keyCertSign
V2022-06-17T09:22:44+000000:tool/net/redbean.c:1862:redbean-demo-2:9928] (ssl) generating self-signed ssl certificates
V2022-06-17T09:22:44+002999:tool/net/redbean.c:610:redbean-demo-2:9928] (ssl) using EC certificate "CN=catalyst" for HTTPS server
V2022-06-17T09:22:45.155965:tool/net/redbean.c:610:redbean-demo-2:9928] (ssl) using RSA certificate "CN=catalyst" for HTTPS server
/C/Users/Zulu//.redbean_history: failed to load history: EUNKNOWN/123/No error information
>: Benchmark(unix.clock_gettime)
error: Uncaught SIGSEGV (SEGV_ACCERR) on catalyst pid 9928 tid 39304
  redbean-demo-2.0.2.com
  EFAULT/487/Bad address/6/The handle is invalid
  The New Technology  catalyst 10.0-19044

00000259e4e0 00000053d7bb fixpathname+62
00000259fcd0 00000053d88f fopen+46
00000259fd10 0000004e2690 linenoiseHistorySave+47
00000259fd40 0000004c9709 pushline+208
00000259fd80 0000004c9cd0 lua_loadline+81
00000259fda0 000000419b42 HandleReadline+474
00000259fdd0 000000419bd9 WindowsReplThread+73
00000259fdf0 00000040d9e3 __nt2sysv+43
00000259ff20 7ffbc53a7034 NULL+0

RAX 0000000000000000 RBX 0000000000000241 RDI 00000000005a1f76 ST(0) 0.0
RCX 0000000000000002 RDX 0000000000000001 RSI 0000000000000000 ST(1) 0.0
RBP 000000000259fcd0 RSP 000000000259fcd0 RIP 000000000053d7bb ST(2) 0.0
 R8 00001000800a31a0  R9 000000000000000c R10 0000000000000000 ST(3) 0.0
R11 000000000259f6b0 R12 0000000000586da9 R13 0000000000000000 ST(4) 0.0
R14 0000000000000001 R15 0000000000000000 VF PF ZF IF

XMM0  0029656d69747465675f6b636f6c632e XMM8  00000000000000000000000000000000
XMM1  632e78696e75286b72616d68636e6542 XMM9  00000000000000000000000000000000
XMM2  000000000000000000001000800af270 XMM10 00000000000000000000000000000000
XMM3  00000000000000000000000000000000 XMM11 00000000000000000000000000000000
XMM4  00000000000000000000000000000000 XMM12 00000000000000000000000000000000
XMM5  00000000000000000000000000000000 XMM13 00000000000000000000000000000000
XMM6  6d39335b1b6b72616d68636d30395b1b XMM14 00000000000000000000000000000000
XMM7  00001000800b8b5000001000800b8b10 XMM15 00000000000000000000000000000000

10008000-10008000 rw-pa-- 1x automap h=156
10008001-10008001 rw-sa-- 1x automap h=372
10008002-10008002 rw-pa-- 1x automap h=380
10008003-10008003 rw-pa-- 1x automap h=384
10008004-10008004 rw-pa-- 1x automap h=400
10008005-10008005 rw-pa-- 1x automap h=396
10008006-10008006 rw-pa-- 1x automap h=392
10008007-10008007 rw-pa-- 1x automap h=388
10008008-10008008 rw-pa-- 1x automap h=324
10008009-10008009 rw-pa-- 1x automap h=480
1000800a-1000800a rw-pa-- 1x automap h=484
1000800b-1000800b rw-pa-- 1x automap h=636
1000800c-1000800c rw-pa-- 1x automap h=604
1000800d-1000800d rw-pa-- 1x automap h=600
1000800e-1000800e rw-pa-- 1x automap h=640
1000800f-1000800f rw-pa-- 1x automap w/ 27 frame hole h=628
1000802b-1000802b r--s--- 1x automap readonlyfile h=408
1000802c-1000802c r--s--- 1x automap readonlyfile h=412
1000802d-1000802d r--s--- 1x automap readonlyfile h=416
1000802e-1000802e r--s--- 1x automap readonlyfile h=420
1000802f-1000802f r--s--- 1x automap readonlyfile size=35'814 h=160
10008030-10008030 r--p--- 1x automap cow h=360
10008031-10008031 r--p--- 1x automap cow h=356
10008032-10008032 r--p--- 1x automap cow h=352
10008033-10008033 r--p--- 1x automap cow h=344
10008034-10008034 r--p--- 1x automap cow h=340
10008035-10008035 r--p--- 1x automap cow h=336
10008036-10008036 r--p--- 1x automap cow h=332
10008037-10008037 r--p--- 1x automap cow h=328
10008038-10008038 r--p--- 1x automap cow h=240
10008039-10008039 r--p--- 1x automap cow h=236
1000803a-1000803a r--p--- 1x automap cow h=232
1000803b-1000803b r--p--- 1x automap cow h=228
1000803c-1000803c r--p--- 1x automap cow h=224
1000803d-1000803d r--p--- 1x automap cow h=220
1000803e-1000803e r--p--- 1x automap cow h=216
1000803f-1000803f r--p--- 1x automap cow h=148
10008040-10008040 r--p--- 1x automap cow h=164
10008041-10008041 r--p--- 1x automap cow h=424
10008042-10008042 r--p--- 1x automap cow h=428
10008043-10008043 r--p--- 1x automap cow h=432
10008044-10008044 r--p--- 1x automap cow h=436
10008045-10008045 r--p--- 1x automap cow h=440
10008046-10008046 r--p--- 1x automap cow h=444
10008047-10008047 r--p--- 1x automap cow h=448
10008048-10008048 r--p--- 1x automap cow h=452
10008049-10008049 r--p--- 1x automap cow h=456
1000804a-1000804a r--p--- 1x automap cow h=460
1000804b-1000804b r--p--- 1x automap cow h=464
1000804c-1000804c r--p--- 1x automap cow h=468
1000804d-1000804d r--p--- 1x automap cow h=472
1000804e-1000804e r--p--- 1x automap cow h=476
1000804f-1000804f r--p--- 1x automap cow size=35'814 w/ 1'607'434'156 frame hole h=364
6fcffffc-6fcffffc rw-pa-F 1x w/ 3'145'729 frame hole h=376
6ffffffe-70000003 rw-Sa-- 6x h=152
# 60 frames mapped w/ 1'610'579'912 frames gapped
redbean-demo-2.0.2.com -Zv
```

**Comment by pkulchenko** [comment] 2022-06-17 23:31
> Windows 10 x64

@Zulu-Inuoe, thank you for the report. I can't reproduce this on the same version of Windows. Everything is executed correctly for me. I'm curious, does this file exist `/C/Users/Zulu//.redbean_history`?

**Comment by Zulu-Inuoe** [comment] 2022-06-17 23:37
Of course, thank you all for writing and maintaining the project.

The file did not exist. I went ahead and created a blank file, but I still get the exact same behaviour (even the line about it not being able to open it). Do notice that there's a double `/` in the path which is a bit odd.

I also tried moving redbean to the C drive in case something about multiple drives was messing it up. No-go either.

I tried running this via my shell (cmder), bare-bones cmd, and finally by itself (double-click on the com file) and they all behave the same

**Comment by Zulu-Inuoe** [comment] 2022-06-18 04:03
@pkulchenko So I was toying around with some things and found this.

On my system, I have set up an environment variable for `HOME` because I use Emacs and a couple of other tools which I have found work more reliably when I do that.
I have it set to `HOME=C:\Users\Zulu\`

Turns out, when I run redbean WITHOUT setting `HOME` at all, it successfully boots up, no longer complaining about failing to find `.redbean_history` and the REPL works without a hitch.

I also tried setting it to `HOME=C:\Users\Zulu` and that also works.
However, `HOME=C:/Users/Zulu/` does not work, while `HOME=C:/Users/Zulu` does work.

So it looks like there's an issue when `HOME` ends in a backslash or forward slash.

**Comment by pkulchenko** [comment] 2022-06-18 05:02
@Zulu-Inuoe, that's very useful, thank you for doing this research. I may have a fix for this shortly.

**Comment by pkulchenko** [comment] 2022-06-18 05:41
@Zulu-Inuoe, I'm curious, does this patch fix the issue for you: https://github.com/pkulchenko/cosmopolitan/commit/335f5ec1d5cbd516f3b69aea51883b4559c78184?

**Comment by jart** [comment] 2022-06-18 08:07
This is a great report. I managed to find three problems I could fix thanks to this issue.

```
- Avoid creating double slash path in linenoise (#428)
- Remove double slashes in NT paths automatically (#428)
- Make strerror() smarter about showing NT errors (#428)
```

A change will be pushed shortly, at which point this issue will be closed. I will shortly after push a 2.0.4 release to https://redbean.dev/ in the next day or so. You'll be able to build it from source until then, if you have access to a Linux computer, by running `make -j8 o//tool/net/redbean.com`.

**Closed** 2022-06-18 08:49 UTC

**Comment by Zulu-Inuoe** [comment] 2022-06-20 12:09
Thanks all! Just confirming that this indeed fixed my issue.
Thanks!
