### ISSUE TITLE
printvideo.com failing on piledriver

### ISSUE THREAD

**Issue by ritschwumm** [jart/cosmopolitan#37] opened 2021-01-31 13:44 UTC
i'm running ubuntu focal on an "AMD FX(tm)-8350 Eight-Core Processor" - 
should this work, or am i missing something?
and if it should, what can i do to help _making_ it work?

**Comment by jart** [comment] 2021-01-31 18:24
Thanks for the report. You can absolutely help! We need to find the faulting instruction pointer address. I've enabled crash reports on the binary and pushed an update. Could you please run these commands:

```sh
export GDB=
rm -f printvideo.com*
wget https://justine.lol/crabrave.mpg
wget https://justine.lol/printvideo.com
wget https://justine.lol/printvideo.com.dbg
./printvideo.com -s crabrave.mpg
```

**Comment by ritschwumm** [comment] 2021-01-31 18:51
well, that's interesting: this build just works without a hitch.

**Comment by jart** [comment] 2021-01-31 18:59
In that case this is likely a duplicate of #16 and I simply forgot to push a new release of the printvideo.com binary. Thanks again for the report! If there's anything else, please file an issue. I'm at your service.

**Closed by jart** 2021-01-31 18:59 UTC

**Comment by jart** [comment] 2021-01-31 19:09
Also would love to hear any feedback you have on the printvideo.com program, while you're here. I wrote it with the goal of making it the best. It has useful keyboard shortcuts like `t` for true color mode, `s` for statistics, `ctrl+g` for unsharp masking. You can even change the illumination parameter to simulate different types of light bulbs by pressing `l` and `L`.

**Comment by ritschwumm** [comment] 2021-02-03 22:37
so.. some feedback, in order of specifity:
* the whole concept of cosmopolitan is amazing, one of the coolest hack's i've ever seen.
* i can't imagine yet where to use it, but sooner or later i'll probably find some application where it's exactly what i need. if i can bring myself to touch C again, which still feels wrong to me after 30 years of coding in quite a few languages.
* with printvideo.com, there's 3 keyboard shortcuts that i instinctively expected to work, and which didn't: `q` for quitting, and cursor righ/left for skipping forward and backwards
* printimage.com which was previously crashing now works for me

**Comment by jart** [comment] 2021-02-03 23:40
Thanks for the feedback.

I believe higher level languages should adopt Cosmopolitan as an implementation detail. It'll give them an advantage that no competitor has, which is tiny performant portable native binaries and painless native modules. The goal of this project is to fix the system integration problem. That'll make life better for everyone regardless of language. Although anyone who enjoys C will find that using Cosmopolitan make writing it much more pleasant.

As for printvideo, I'm going to add the `q` shortcut, since there's no excuse for not having it. I agree that left/right seek shortcuts should happen which I worked to address in the past but ended up kicking the can down the road. Contributions are welcome on that one.
