### ISSUE TITLE
Bug: DNS resolution on windows

### ISSUE THREAD

**Issue by theimpostor** [jart/cosmopolitan#1310] opened 2024-10-04 21:39 UTC
### What happened?

Trying to use the ape binaries on Windows 11, hostname lookup seems to fail when running the prebuilt fat binaries under bash.

Downloaded https://cosmo.zip/pub/cosmos/zip/cosmos-3.9.2.zip and https://cosmo.zip/pub/cosmos/zip/git.zip, extracted to `C:\`. In a `/bin/bash -l` shell, trying to clone this repo fails with `Could not resolve host: github.com`, using `curl` fails similarly. `curl` works from a regular windows command prompt.

Other commands like `unzip`, `ls`, `bash` etc seem to work fine.

### Version

cosmos 3.9.2

### What operating system are you seeing the problem on?

Windows

**Comment by jart** [comment] 2024-10-06 05:27
Is your Windows machine IPv6 only?

If you have IPv4 then what's under SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces?

See also https://github.com/jart/cosmopolitan/blob/master/third_party/musl/resolvconf.c the code that does this.

**Comment by theimpostor** [comment] 2024-10-06 22:14
IPV4 is enabled, under HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces there are a number of interfaces listed. 

Also I copied the ape `curl` binary to `cosmocurl.exe` and ran: 
```
cosmocurl --strace https://cosmo.zip/pub/cosmos/bin/unzip 2> curl.txt
```
Attached is the output: [curl.txt](https://github.com/user-attachments/files/17271079/curl.txt)

**Comment by jart** [comment] 2024-10-07 00:20
This line interests me.

```
SYS [1;30m 30184[0m [1;31m 25572[0m         52'042'165 send(6, u"", 1, MSG_NOSIGNAL) → -1 EINVAL
```

Looks like I'm able to reproduce. Thanks for the heads up. I'll have this fixed in a few days for you.

**Comment by jart** [comment] 2024-10-08 01:43
@ahgamut This could be an issue with curl. I'm noticing that curl works fine if I build it at head. Could we upgrade curl in superconfigure?

**Comment by ahgamut** [comment] 2024-10-09 03:57
`curl` built with https://github.com/jart/cosmopolitan/commit/ad11fc32ad0ad9048b4b39f49b5ef682447cff81

https://github.com/ahgamut/superconfigure/releases/download/z0.0.57/web.zip

**Comment by jart** [comment] 2024-10-09 04:04
@theimpostor could you confirm the fix works for you?

**Comment by jart** [comment] 2024-10-09 04:09
@ahgamut To make curl work, I built it at curl/curl@a79f20d37612fbc1150a01840967b95a210a574d could we use that?

**Comment by ahgamut** [comment] 2024-10-10 03:51
the new superconfigure release builds `curl-8.10.1` with `libpsl`, which IIUC should fix this error:

https://github.com/ahgamut/superconfigure/releases/download/z0.0.58/web.zip

**Comment by theimpostor** [comment] 2024-10-10 12:58
> the new superconfigure release builds `curl-8.10.1` with `libpsl`, which IIUC should fix this error:
> 
> https://github.com/ahgamut/superconfigure/releases/download/z0.0.58/web.zip

`git` and `curl` appear to be working with that release. Thank you!

**Comment by jart** [comment] 2024-10-11 00:09
Hooray! Glad we could be of service.

**Closed by jart** 2024-10-11 00:09 UTC
Labels: medium severity
