### ISSUE TITLE
Redbean demo segfaults on M1 Mac

### ISSUE THREAD

**Issue by sarna** [jart/cosmopolitan#548] opened 2022-08-18 17:20 UTC
It segfaults after some time both with Rosetta and without it. Running the `fetch.lua` query seems to make it segfault faster.

<details><summary>With Rosetta</summary>

```
error: Uncaught SIGSEGV (SEGV_MAPERR) on sarnas-MacBook-Air pid 71626 tid 259
  /Users/sarna/Downloads/redbean-demo-2.0.16.com
  EUNKNOWN/0/No error information
  XNU's Not UNIX!  sarnas-MacBook-Air

70000003ce20 000000587ab3 __sigenter_xnu+723
70000003ee90 d19156a93086d471 NULL+0
70000003fee0 00000042bb6c HandlePoll+37
70000003ff00 00000042bf66 EventLoop+283
70000003ff30 00000042bfcd ReplEventLoop+82
70000003ff50 00000042c599 RedBean+1384
70000003ffc0 00000042c5cb main+45
70000003ffe0 000000402b5d cosmo+71
0001042037a0 000000402404 _start+130

RAX 0000000000000180 RBX 0000000000000040 RDI 000070000003ec08 ST(0) -18437520701672696841.18446744073709550808
RCX 000000010015e3f0 RDX 0000000000000000 RSI 0000000000000001 ST(1) -18437520701672696841.18446744073709550808
RBP 000070000003ee90 RSP 000070000003eab0 RIP 0000000000587ab3 ST(2) -18437520701672696841.18446744073709550808
 R8 000000010015e088  R9 0000000000000014 R10 0000000000000023 ST(3) -18437520701672696841.18446744073709550808
R11 0000000002000000 R12 0000000000000001 R13 000000010015e088 ST(4) -18437520701672696841.18446744073709550808
R14 00000001042037e0 R15 00000001042037b0 VF IF PE

XMM0  00000000000000000000000000000000 XMM8  00000001c6e415960000000154442bd4
XMM1  00000000000000000000000000000000 XMM9  7558677a4529087f7480dfde3c5b6903
XMM2  00000000000000000000000000000000 XMM10 00000000000000000000000000000000
XMM3  000000000000000000001000800ffc70 XMM11 00000000000000000000000000000000
XMM4  000000000000000000000000000000de XMM12 00000000000000000000000000000000
XMM5  0000100080123b500000100080123b30 XMM13 00000000000000000000000000000000
XMM6  0079646f4265736e6f70736552746547 XMM14 00000000000000000000000000000000
XMM7  00001000801227b00000100080122770 XMM15 00000000000000000000000000000000

10008000-1000800b rw-pa-- 12x automap
1000800c-1000800c rw-sa--  1x automap
1000800d-10008012 rw-pa--  6x automap w/ 1 frame hole
10008014-10008015 rw-pa--  2x automap w/ 39 frame hole
1000803d-10008041 r--s---  5x automap size=300'308 w/ 30 frame hole
10008060-10008081 r--p--- 34x automap size=2'200'852 w/ 1'607'434'106 frame hole
6fcffffc-6fcffffc rw-pa-F  1x
70000000-70000003 rw-Sa--  4x stack
# 65 frames mapped w/ 1'607'434'176 frames gapped
/Users/sarna/Downloads/redbean-demo-2.0.16.com
```

</details>

<details><summary>Without Rosetta</summary>

```
error: Uncaught SIGSEGV (SEGV_MAPERR) on sarnas-MacBook-Air pid 72544 tid 515
  ./redbean-demo-2.0.16.com
  EUNKNOWN/0/No error information
  XNU's Not UNIX!  sarnas-MacBook-Air 

70000003c310 000000587ab3 __sigenter_xnu+723
70000003e380 bac0770a7c490005 NULL+0
70000003f3d0 00000057027e wait4+59
70000003f420 0000004dae86 LuaUnixWait+98
70000003f4f0 0000004bb5a5 luaD_precall+189
70000003f540 0000004d77e0 luaV_execute+14461
70000003f6e0 0000004bb798 ccall+84
70000003f710 0000004bb7f3 resume+68
70000003f740 0000004bab80 luaD_rawrunprotected+84
70000003f7c0 0000004bb916 lua_resume+152
70000003f800 0000004cf544 LuaCallWithTrace+122
70000003f860 00000041a5c7 LuaCallWithYield+59
70000003f8f0 000000428c4d ServeLua+172
70000003f930 000000428dd5 HandleAsset+235
70000003f940 000000429837 RoutePath+102
70000003f970 000000429ddb Route+90
70000003f9a0 000000429ed2 LuaRoute+85
70000003f9d0 0000004bb5a5 luaD_precall+189
70000003fa20 0000004d77e0 luaV_execute+14461
70000003fbc0 0000004bb798 ccall+84
70000003fbf0 0000004bb7f3 resume+68
70000003fc20 0000004bab80 luaD_rawrunprotected+84
70000003fca0 0000004bb916 lua_resume+152
70000003fce0 0000004cf544 LuaCallWithTrace+122
70000003fd40 00000041a5c7 LuaCallWithYield+59
70000003fdd0 000000428e88 LuaOnHttpRequest+81
70000003fdf0 00000042a2a9 HandleRequest+943
70000003fe40 00000042a303 HandleMessageActual+85
70000003fe80 00000042a69b HandleMessage+21
70000003fe90 00000042afe7 HandleMessages+157
70000003feb0 00000042b542 HandleConnection+161
70000003fee0 00000042bc46 HandlePoll+255
70000003ff00 00000042bf66 EventLoop+283
70000003ff30 00000042bfcd ReplEventLoop+82
70000003ff50 00000042c599 RedBean+1384
70000003ffc0 00000042c5cb main+45
70000003ffe0 000000402b5d cosmo+71
00010462f210 000000402404 _start+130

RAX 0000000000000180 RBX 0000000000000040 RDI 000070000003e0f8 ST(0) -18437520701672696841.18446744073709550808
RCX 00000001005a03f0 RDX 00001000800a2488 RSI 0000000000000001 ST(1) -18437520701672696841.18446744073709550808
RBP 000070000003e380 RSP 000070000003dfa0 RIP 0000000000587ab3 ST(2) -18437520701672696841.18446744073709550808
 R8 00001000800aa1a0  R9 6567617375522e78 R10 000070000003db50 ST(3) -18437520701672696841.18446744073709550808
R11 0000000002000000 R12 0000000000000001 R13 00000001005a0088 ST(4) -18437520701672696841.18446744073709550808
R14 0000000000000000 R15 000070000003f440 VF IF ZE PE

XMM0  00000000000000000000000000000000 XMM8  00000001c6e415960000000154442bd4
XMM1  00000000000000000000000000000000 XMM9  200a6563f181b01d2327521cf3c38851
XMM2  00000000000000000000000000000000 XMM10 00000000000000000000000000000000
XMM3  00000000000000000000000000000000 XMM11 00000000000000000000000000000000
XMM4  000000000000000000000000000000de XMM12 00000000000000000000000000000000
XMM5  00000000000000000000000000000000 XMM13 00000000000000000000000000000000
XMM6  00000000000000010000000000000000 XMM14 00000000000000000000000000000000
XMM7  00000000000000000000000000000001 XMM15 00000000000000000000000000000000

10008000-1000800b rw-pa-- 12x automap
1000800c-1000800c rw-sa--  1x automap
1000800d-10008012 rw-pa--  6x automap w/ 1 frame hole
10008014-1000801b rw-pa--  8x automap w/ 33 frame hole
1000803d-10008041 r--s---  5x automap size=300'308 w/ 30 frame hole
10008060-10008081 r--p--- 34x automap size=2'200'852 w/ 1'607'434'106 frame hole
6fcffffc-6fcffffc rw-pa-F  1x
70000000-70000003 rw-Sa--  4x stack  
# 71 frames mapped w/ 1'607'434'170 frames gapped
./redbean-demo-2.0.16.com 

error: Uncaught SIGSEGV (SEGV_MAPERR) on sarnas-MacBook-Air pid 72512 tid 259
  ./redbean-demo-2.0.16.com
  EUNKNOWN/0/No error information
  XNU's Not UNIX!  sarnas-MacBook-Air 

70000003ce20 000000587ab3 __sigenter_xnu+723
70000003ee90 e37a9924f973887d NULL+0
70000003fee0 00000042bb6c HandlePoll+37
70000003ff00 00000042bf66 EventLoop+283
70000003ff30 00000042bfcd ReplEventLoop+82
70000003ff50 00000042c599 RedBean+1384
70000003ffc0 00000042c5cb main+45
70000003ffe0 000000402b5d cosmo+71
00010462f210 000000402404 _start+130

RAX 0000000000000180 RBX 0000000000000040 RDI 000070000003ec08 ST(0) -18437520701672696841.18446744073709550808
RCX 000000010055a3f0 RDX 0000000000000000 RSI 0000000000000001 ST(1) -18437520701672696841.18446744073709550808
RBP 000070000003ee90 RSP 000070000003eab0 RIP 0000000000587ab3 ST(2) -18437520701672696841.18446744073709550808
 R8 000000010055a088  R9 0000000000000014 R10 0000000000000023 ST(3) -18437520701672696841.18446744073709550808
R11 0000000002000000 R12 0000000000000001 R13 000000010055a088 ST(4) -18437520701672696841.18446744073709550808
R14 000000010462f250 R15 000000010462f220 VF IF PE

XMM0  00000000000000000000000000000000 XMM8  00000001c6e415960000000154442bd4
XMM1  00000000000000000000000000000000 XMM9  7558677a4529087f7480dfde3c5b6903
XMM2  00000000000000000000000000000000 XMM10 00000000000000000000000000000000
XMM3  000000000000000000001000800fdee0 XMM11 00000000000000000000000000000000
XMM4  000000000000000000000000000000de XMM12 00000000000000000000000000000000
XMM5  00001000800fe53000001000800fe510 XMM13 00000000000000000000000000000000
XMM6  0074636572696465526d6172676f7250 XMM14 00000000000000000000000000000000
XMM7  00001000800fdd0000001000800fdcc0 XMM15 00000000000000000000000000000000

10008000-1000800b rw-pa-- 12x automap
1000800c-1000800c rw-sa--  1x automap
1000800d-10008012 rw-pa--  6x automap w/ 1 frame hole
10008014-10008015 rw-pa--  2x automap w/ 39 frame hole
1000803d-10008041 r--s---  5x automap size=300'308 w/ 30 frame hole
10008060-10008081 r--p--- 34x automap size=2'200'852 w/ 1'607'434'106 frame hole
6fcffffc-6fcffffc rw-pa-F  1x
70000000-70000003 rw-Sa--  4x stack  
# 65 frames mapped w/ 1'607'434'176 frames gapped
./redbean-demo-2.0.16.com 
```

</details>

"With Rosetta" I run it in an iTerm2 with Rosetta enabled, didn't use any extra commands. "Without Rosetta" I ran it like this:
```
$ arch -x86_64 ./redbean-demo-2.0.16.com --assimilate
$ ./redbean-demo-2.0.16.com
```

System info:
```
sarna@sarnas-MacBook-Air ~> uname -a
Darwin sarnas-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64
```

I can provide more info, just let me know what and how to collect it :)

**Comment by pkulchenko** [comment] 2022-08-18 17:26
@sarna, thank you for the detailed results! This appears to be a duplicate of #455, even though that ticket was specifically about signal handling under Rosetta, as it looked at that time that the issue was limited to Rosetta only. I wonder if commenting out `SigInit` in redbean (as discussed in #455) "fixes" the issue for runs "without Rosetta" too.

**Comment by sarna** [comment] 2022-08-18 17:30
@pkulchenko, that's interesting! I've seen this issue but I thought it was something different. I'll try building with `SigInit` commented out and report back.

**Comment by jart** [comment] 2022-08-18 22:47
Marking as a duplicate of #455 let's move talk there. Thanks for the report!

**Closed by jart** 2022-08-18 22:47 UTC

**Comment by dkulchenko** [comment] 2022-08-18 23:36
Confirmed dupe of #455. I was able to repro the segfault on the normal build, but after commenting out `SigInit`, I wasn't able to get it to crash, even after slamming it with requests with `wrk`.
